### PR TITLE
Release `1.1.0`

### PR DESCRIPTION
**Pull request by robbot006**
This is a draft of changelog for the `1.1.0` release.
Here you can find all related translations changes: [1.0.1...main](https://github.com/flarum-lang/swedish/compare/1.0.1...main).

> ### ⚠️ Do not merge this pull request manually ⚠️
> 
> You should **[approve](https://github.com/rob006-software/flarum-translations/wiki/How-to-approve-release-pull-request)** this pull request instead. After approving, I will automatically update it (release date needs to be adjusted), merge, and tag a new release.

<details>
<summary>Show release notes preview</summary>

## 1.1.0

**General changes**:

* Updated Flarum core translations.
* Updated validation translations.

**Added support for new extensions**:

* [`clarkwinkelmann/flarum-ext-group-invitation`](https://github.com/clarkwinkelmann/flarum-ext-group-invitation)
* [`fof/github-sponsors`](https://github.com/FriendsOfFlarum/github-sponsors)
* [`fof/share-social`](https://github.com/FriendsOfFlarum/share-social)
* [`fof/socialprofile`](https://github.com/FriendsOfFlarum/socialprofile)
* [`fof/stopforumspam`](https://github.com/FriendsOfFlarum/stopforumspam)
* [`nearata/flarum-ext-twofactor`](https://github.com/Nearata/flarum-ext-twofactor)

**Updated translations for extensions**:

* [`flarum/akismet`](https://github.com/flarum/akismet)
* [`flarum/approval`](https://github.com/flarum/approval)
* [`flarum/emoji`](https://github.com/flarum/emoji)
* [`flarum/flags`](https://github.com/flarum/flags)
* [`flarum/likes`](https://github.com/flarum/likes)
* [`flarum/lock`](https://github.com/flarum/lock)
* [`flarum/markdown`](https://github.com/flarum/markdown)
* [`flarum/mentions`](https://github.com/flarum/mentions)
* [`flarum/nicknames`](https://github.com/flarum/nicknames)
* [`flarum/pusher`](https://github.com/flarum/pusher)
* [`flarum/statistics`](https://github.com/flarum/statistics)
* [`flarum/sticky`](https://github.com/flarum/sticky)
* [`flarum/subscriptions`](https://github.com/flarum/subscriptions)
* [`flarum/suspend`](https://github.com/flarum/suspend)
* [`flarum/tags`](https://github.com/flarum/tags)

All changes: [1.0.1...1.1.0](https://github.com/flarum-lang/swedish/compare/1.0.1...1.1.0).

</details>

### CODE REVIEW

**Comment by rob006** [comment]
@Dzenan @gustjoha Just as a note, this is an automated PR generated by bot. The idea is to simplify release process for language pack maintainers - all you need is to approve this pull request and bot will handle the rest. You can read more about the process at forum: https://discuss.flarum.org/d/20807-simplify-translation-process-with-weblate/76 . If you don't want to use this feature, let me know.

BTW: @gustjoha  it looks like you don't have maintainer permissions on Weblate. Do you want it?

**Review by gustjoha — APPROVED** [review]

**Comment by robbot006** [comment]
Success! Now you can announce new release on [forum](https://discuss.flarum.org/t/languages):

~~~markdown
## Version [`1.1.0`](https://github.com/flarum-lang/swedish/releases/tag/1.1.0)

**General changes**:

* Updated Flarum core translations.
* Updated validation translations.


**Added support for new extensions**:

* [`clarkwinkelmann/flarum-ext-group-invitation`](https://github.com/clarkwinkelmann/flarum-ext-group-invitation)
* [`fof/github-sponsors`](https://github.com/FriendsOfFlarum/github-sponsors)
* [`fof/share-social`](https://github.com/FriendsOfFlarum/share-social)
* [`fof/socialprofile`](https://github.com/FriendsOfFlarum/socialprofile)
* [`fof/stopforumspam`](https://github.com/FriendsOfFlarum/stopforumspam)
* [`nearata/flarum-ext-twofactor`](https://github.com/Nearata/flarum-ext-twofactor)


**Updated translations for extensions**:

* [`flarum/akismet`](https://github.com/flarum/akismet)
* [`flarum/approval`](https://github.com/flarum/approval)
* [`flarum/emoji`](https://github.com/flarum/emoji)
* [`flarum/flags`](https://github.com/flarum/flags)
* [`flarum/likes`](https://github.com/flarum/likes)
* [`flarum/lock`](https://github.com/flarum/lock)
* [`flarum/markdown`](https://github.com/flarum/markdown)
* [`flarum/mentions`](https://github.com/flarum/mentions)
* [`flarum/nicknames`](https://github.com/flarum/nicknames)
* [`flarum/pusher`](https://github.com/flarum/pusher)
* [`flarum/statistics`](https://github.com/flarum/statistics)
* [`flarum/sticky`](https://github.com/flarum/sticky)
* [`flarum/subscriptions`](https://github.com/flarum/subscriptions)
* [`flarum/suspend`](https://github.com/flarum/suspend)
* [`flarum/tags`](https://github.com/flarum/tags)


All changes: [1.0.1...1.1.0](https://github.com/flarum-lang/swedish/compare/1.0.1...1.1.0).

In order to update run these commands:

```console
composer update flarum-lang/swedish
php flarum cache:clear
```

~~~

**Comment by gustjoha** [comment]
> 

Hi Rob,
You can give me admin status on Weblate, username gustjoha. 

I cannot promise that i will translate everything right now but maybe I will have more time in the future.

**Comment by rob006** [comment]
> You can give me admin status on Weblate, username gustjoha.

Done.

> I cannot promise that i will translate everything right now but maybe I will have more time in the future.

If you don't have time to translate, that is fine, we can't force anyone to translate. :) We're mostly concerned about lack of reviews and releases, since by default Composer will not install unreleased changes. So as long as you will be able to review translations contributed by community through Weblate, and tag new releases (it should be easier now, thanks to PRs like this), it is fine.

**Pull request merged**
